### ISSUE TITLE
The stop button on the main widget panel doesn't work

### ISSUE THREAD

**Issue by AlienQueen** [mika-nt28/Jeedom-Plex#4]

**Comment by mika-nt28** [comment]
Lorsque je regarde mes log debug lors que j'appuie sur le stop j'obtient
`[2016-11-28` 09:02:18][DEBUG] : Connexion a http://192.168.x.x:xxxx/player/playback/stop?X-Plex-Token=xxxxxxxxx
[2016-11-28 09:02:18][DEBUG] : response: <?xml version="1.0" encoding="utf-8" ?> <Response code="200" status="OK" />`
La mise en forme de l'url est correcte et j'ai bien un reponse de rasplex.
Je testerai en face de mon ecran mais pour moi cela fonctionne
