### ISSUE TITLE
Pas de demon 

### ISSUE THREAD

**Issue by Blacksly** [mika-nt28/Jeedom-Plex#43]
Bonjour, 

Suite à l'installation et l'activation du plugin je n'ai pas de démon qui apparaît ... 

Une idée ? Merci :)

**Comment by romaindevjeed** [comment]
Bonjour,

Pas de demon non plus.

Merci pour votre aide.

**Comment by mika-nt28** [comment]
Désolé je viens de me rendre compte de ce message
Est réglé depuis ou le problème existe toujours

**Comment by Blacksly** [comment]
Pas de soucis :) 

Je viens de vérifier à l'instant et oui toujours pareil :/

**Comment by mika-nt28** [comment]
Y as t'il des log en debug?
Est ce que les clients sont trouvé et les télécommande fonctionnel?

**Comment by mika-nt28** [comment]
Normalement corrigé dans la derniere stable
