### ISSUE TITLE
Erreur actualisation

### ISSUE THREAD

**Issue by Sigri44** [mika-nt28/Jeedom-plex#54]
Hello,

Sur le dashboard, j'ai ce message tout en haut depuis l'ajout d'un client Plex : 
×The section "" was not found.

![image](https://user-images.githubusercontent.com/9304947/67548171-74e98600-f701-11e9-9eae-9926c72e2a91.png)

Merci

**Comment by Sigri44** [comment]
![image](https://user-images.githubusercontent.com/9304947/67617967-f8ca6d80-f7e8-11e9-9696-ff17934cdbac.png)

**Comment by mika-nt28** [comment]
Sur le widget il faut choisir le serveur 
Il arrive parfois que la selection automatique ne fonctionne pas correctement

Pour avoir plus de visibilité et un reponse plus rapide je vous invite a utilisé le site community

**Comment by Sigri44** [comment]
Hello !

Il est bien sélectionné pourtant, dans le code source, l'input (en hidden) est bien rempli par le client.

<img width="715" alt="Capture d’écran 2019-11-12 à 09 58 20" src="https://user-images.githubusercontent.com/9304947/68656950-0d21a080-0533-11ea-902b-797dfa3189b8.png">

Désolé je ne suis plus autorisé à accéder à Community.

Merci
